In [3]:
import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score,root_mean_squared_error, mean_absolute_error
df=pd.read_csv('modelready.csv')

In [4]:
df

,seed,Team/Year,AdjTempo,AdjOE,AdjDE,AdjEM,OppeFGPct,OppTOPct,OppORPct,OppFTRate,eFGPct,TOPct,ORPct,FTRate
0,2.0,2002 Alabama,67.8101,114.1770,94.1585,20.01810,46.017700,22.033500,34.894300,33.284200,49.179100,20.026700,40.173600,40.753300
1,16.0,2002 Alcorn St.,72.5438,99.7682,108.1700,-8.40177,48.726800,21.550500,33.333300,35.066300,50.692600,22.587000,39.459900,40.490100
2,3.0,2002 Arizona,71.2261,119.2120,97.3917,21.81990,49.237700,18.289000,35.976100,28.520200,52.156900,18.964900,35.332800,44.607800
3,11.0,2002 Boston College,69.0270,109.5160,99.2719,10.24390,47.470100,22.563600,37.887700,42.328600,47.412400,19.748600,37.355400,40.564600
4,16.0,2002 Boston University,64.2616,100.9710,103.1680,-2.19695,45.454500,19.870000,32.013500,37.215900,48.075800,19.727400,34.902300,36.842100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1328,12.0,2023 VCU,68.0086,107.1950,94.0449,13.14980,46.899632,23.944075,29.958159,31.108776,51.955008,19.590607,28.851291,41.564006
1329,15.0,2023 Vermont,64.6048,109.7780,104.3570,5.42124,51.043383,16.588859,22.316384,26.908292,54.833424,14.251754,19.234450,28.126707
1330,4.0,2023 Virginia,61.5696,111.1660,94.7544,16.41140,48.281887,19.478597,24.881292,26.324985,51.161473,13.630185,25.609756,34.730878
1331,9.0,2023 West Virginia,68.8537,117.1440,97.9996,19.14450,50.888530,20.882782,29.319853,38.664513,51.510497,18.525048,34.014210,39.375320
1332,3.0,2023 Xavier,70.3573,119.2970,99.6040,19.69300,50.284464,16.239932,25.018450,27.045952,55.230496,17.175412,30.744337,31.382979